//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBillingInfoView
    {
        public int JobLogId { get; set; }
        public int DutyId { get; set; }
        public int TeamId { get; set; }
        public bool CompanyVehicle { get; set; }
        public int BillableQuantity { get; set; }
        public byte PayrollPeriod { get; set; }
        public string PayrollYear { get; set; }
        public int EmployeeId { get; set; }
        public decimal Rate { get; set; }
        public string Contractor { get; set; }
        public string TicketNo { get; set; }
        public System.DateTime JobDate { get; set; }
        public string JobDescription { get; set; }
        public string SiteAddress { get; set; }
        public string TelephoneNo { get; set; }
        public int LeadContractor { get; set; }
        public string EmployeeRef { get; set; }
        public string DutyCode { get; set; }
        public string ClientCodeDescription { get; set; }
        public string Region { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsBilled { get; set; }
        public int DiaryTemplateId { get; set; }
        public short RegionId { get; set; }
        public int BusinessLineId { get; set; }
        public string Service { get; set; }
        public string QA100 { get; set; }
        public string WRK { get; set; }
        public string RG6M { get; set; }
        public string RG6l { get; set; }
        public string RG11 { get; set; }
        public string AMPS { get; set; }
        public string SPLIT { get; set; }
        public string CustomerName { get; set; }
        public string ServiceOrderNo { get; set; }
    }
}
