//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Adjustment
    {
        public int AdjustmentId { get; set; }
        public int JobLogId { get; set; }
        public byte PayrollPeriod { get; set; }
        public string PayrollYear { get; set; }
        public short AdjustmentTypeId { get; set; }
        public decimal AdjustmentAmount { get; set; }
        public string AdjustmentNote { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
    }
}
