//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_BusinessLine
    {
        public int BusinessLineId { get; set; }
        public string BusinessLineDescription { get; set; }
        public bool Active { get; set; }
    }
}
