//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Config
    {
        public short CompanyId { get; set; }
        public string OrgUnitName { get; set; }
        public string TicketNumberFormat { get; set; }
        public byte TicketNoMinLength { get; set; }
        public bool RequireJobTimes { get; set; }
        public bool EnabledJobTimes { get; set; }
        public short MaxDaysInTheBack { get; set; }
        public short PrimaryContractorsOrgUnitId { get; set; }
        public short SecondaryContractorsOrgUnitId { get; set; }
        public string HFCTicketNumberFormat { get; set; }
        public Nullable<byte> HFCTicketNoMinLength { get; set; }
        public bool CreateTeamsOnTheFly { get; set; }
        public string BillingExportOrder { get; set; }
        public bool SeparateLateJobsInExport { get; set; }
    }
}
