//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_PayrollConfig
    {
        public int PayrollConfigId { get; set; }
        public int PayrollYear { get; set; }
        public int PayrollPeriod { get; set; }
        public System.DateTime OpenDate { get; set; }
        public System.DateTime CloseDate { get; set; }
        public bool Active { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
