//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobLogDetailsView
    {
        public int JobLogId { get; set; }
        public int DutyId { get; set; }
        public int TeamId { get; set; }
        public bool CompanyVehicle { get; set; }
        public decimal BillableQuantity { get; set; }
        public byte PayrollPeriod { get; set; }
        public string PayrollYear { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string Contractor { get; set; }
        public string TicketNo { get; set; }
        public System.DateTime JobDate { get; set; }
        public string JobDescription { get; set; }
        public string SiteAddress { get; set; }
        public string TelephoneNo { get; set; }
        public int LeadContractor { get; set; }
        public string EmployeeRef { get; set; }
        public string PayrollCode { get; set; }
        public string DutyCode { get; set; }
        public Nullable<bool> IsExported { get; set; }
        public string Region { get; set; }
        public int AdjustmentId { get; set; }
    }
}
