//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContractorManagementEntities : DbContext
    {
        public ContractorManagementEntities()
            : base("name=ContractorManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CM_PayrollConfig> CM_PayrollConfig { get; set; }
        public virtual DbSet<TransactionImport> TransactionImports { get; set; }
        public virtual DbSet<TransactionImportAccountNo> TransactionImportAccountNoes { get; set; }
        public virtual DbSet<ClientBillingInfoView> ClientBillingInfoViews { get; set; }
        public virtual DbSet<CM_Config> CM_Config { get; set; }
        public virtual DbSet<CM_DiaryTemplate> CM_DiaryTemplate { get; set; }
        public virtual DbSet<ImportedTransactionsView> ImportedTransactionsViews { get; set; }
        public virtual DbSet<SystemSecurityConfiguration> SystemSecurityConfigurations { get; set; }
        public virtual DbSet<SystemUserSetting> SystemUserSettings { get; set; }
        public virtual DbSet<SystemUserView> SystemUserViews { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<CM_Adjustment> CM_Adjustment { get; set; }
        public virtual DbSet<CM_AdjustmentType> CM_AdjustmentType { get; set; }
        public virtual DbSet<JobLogDetailsView> JobLogDetailsViews { get; set; }
        public virtual DbSet<CM_BusinessLine> CM_BusinessLine { get; set; }
        public virtual DbSet<RegionView> RegionViews { get; set; }
        public virtual DbSet<CM_ClientCode> CM_ClientCode { get; set; }
    }
}
