//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionView
    {
        public short RegionId { get; set; }
        public short CompanyId { get; set; }
        public string Region { get; set; }
        public string Description { get; set; }
        public string RegionDescription { get; set; }
    }
}
