//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUserView
    {
        public int SystemUserId { get; set; }
        public int MenuId { get; set; }
        public int MenuNodesId { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public byte[] UserImage { get; set; }
        public bool AccountExpirable { get; set; }
        public Nullable<int> ActivePeriod { get; set; }
        public bool RequireUserChange { get; set; }
        public string MenuDescription { get; set; }
        public string ControlName { get; set; }
        public string NodeDescription { get; set; }
        public string NodeControlName { get; set; }
        public Nullable<System.DateTime> AccountExpirationDate { get; set; }
    }
}
