//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemSecurityConfiguration
    {
        public int SystemSecurityConfigurationId { get; set; }
        public bool EnableAutoLogOut { get; set; }
        public int AutoLogOutMinutes { get; set; }
    }
}
