//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionImport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionImport()
        {
            this.TransactionImportAccountNoes = new HashSet<TransactionImportAccountNo>();
        }
    
        public int TransactionImportId { get; set; }
        public string FileName { get; set; }
        public string SheetName { get; set; }
        public int RecordCount { get; set; }
        public int SelectedStartRow { get; set; }
        public string ReferencedColumn { get; set; }
        public int PayrollYear { get; set; }
        public int PayrollPeriod { get; set; }
        public bool IsExported { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ExportedBy { get; set; }
        public Nullable<System.DateTime> DateExported { get; set; }
        public bool DifferenceRecovered { get; set; }
        public string RecoveredBy { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public string ReferencedDateColumn { get; set; }
        public int BusinessLineId { get; set; }
        public int RegionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionImportAccountNo> TransactionImportAccountNoes { get; set; }
    }
}
