//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartReconciliator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionImportAccountNo
    {
        public int TransactionImportAccountNoId { get; set; }
        public int TransactionImportId { get; set; }
        public string JobNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
    
        public virtual TransactionImport TransactionImport { get; set; }
    }
}
